### ISSUE TITLE
Freezing during inference

### ISSUE THREAD

**Issue by cooperlab** [DigitalSlideArchive/HistomicsStream#108]
@Leengit we have a large project (~5000 HS studies) and the inference hangs frequently without displaying an error message. Sometimes this happens in < 1 hour and so we are getting through this ~50-100 jobs at a time by restarting the docker. These is no error message. It is definitely happening during the inference step e.g. `15/Unknown - 123s 7s/step`. I have verified that this happens with with Jupyter and command-line scripts, with single and multi-gpu, and with small and large batch sizes. None of these parameters seem to have an effect on the frequency.

**Comment by Leengit** [comment]
Can I get access to your failing example?  If that's not feasible, what do you recommend for constructing my own?  I can make 100 copies of an image and try to read them all in using histomics_stream; what parameters (e.g., tile size) would be appropriate?  Can you provide me a model that, even if it isn't the one you are using, should stress the system sufficiently to show the problem?

**Comment by cooperlab** [comment]
Hi Lee - I see this on all datasets I use. They don't necessarily have to be large, even tiny biopsies can provoke the problem.

Sending details on an example by email.
