### ISSUE TITLE
3D output formats

### ISSUE THREAD

**Issue by cooperlab** [DigitalSlideArchive/HistomicsStream#6]
Define 3D output formats that preserve spatial organization of analyzed tiles (i.e. x_tile x y_tile x features). Can support subsequent analysis with convolutional networks. Need to use sparse tensor where tiling is not regular, for instance when a tissue mask is used.

**Comment by Leengit** [comment]
Currently the behavior of `histomics_stream` (e.g., version 2.1.8) is to assume that every image is `RGB` or `RGBA`.  Furthermore `histomics_stream` keeps only the first three, which throws away the `A` in `RGBA`.  What is the desired behavior?

To put a proposal out there for discussion: we could allow the user to specify a  list, tuple, or set of feature indices to retain.  That is, `[0,1,2]` or `list(range(3))` would indicate that we should retain the first three features, which is the current behavior.  If the user supplies the string `"all"` then that would retain all features.  Perhaps other use cases?

**Comment by Leengit** [comment]
For the current issue, to support extracted features, I am unsure by what we mean by sparse.  Do we mean any of:

1. For every possible pixel (or, alternatively, for every possible tile in our grid) we will have _exactly one_ feature vector?  Here a feature vector is, say, a set of 1024 values.  This might be implemented as a non-sparse tensor with indices (in C storage order) `[row, column, feature]` or `[feature, row, column]`
2. For every possible pixel (or, alternatively, for every possible tile in our grid) we will have _one or more_ feature vectors?
3. For every possible pixel (or, alternatively, for every possible tile in our grid) we will have _zero or more_ feature vectors?

If masked and unmasked pixels (or, alternatively, tiles) are handled differently, that might mean we are always in case 3??

As has already been said ... for the first, we can do this as an ordinary tensor.  With the first and second, and maybe with the third, we could instead use xarray, etc. to make it more like a database table, where the 4 or 5 columns are for `row`, `column`, `vector`, `feature`, and `value`.  For the pixel at `[row, column]`, `vector` describes which of the one or more feature vectors we are talking about, `feature` describes which of the 1024 values in that feature vector, and `value` is the value of that feature.

Or something between these extremes, such as columns for `row`, `column`, `vector`, `feature0`, ..., `feature1023`.

**Comment by cooperlab** [comment]
Sparse in the width, height dimensions due to masking of background tiles. If we were storing these in an HDF5 I would capture the 2D feature array, and 1D arrays for the the x, y locations of the corresponding tiles which is essentially a sparse array. I would also capture some of the scalar information from the slide or study dictionaries to hep make sense of the contents.

Maybe we can discuss what considerations with @thewtex before choosing a format.

**Comment by Leengit** [comment]
@cooperlab says this is done.
