### ISSUE TITLE
ENH: Support PyTorch

### ISSUE THREAD

**Issue by Leengit** [DigitalSlideArchive/HistomicsStream#79]
Much as we can currently create a TensorFlow Dataset for use in TensorFlow, implement the corresponding feature for PyTorch.

Subtasks:
- [x] Separate the mapping of tiles to chunks from the TensorFlow-specific code so that it can be used for PyTorch as well
- [x] Remove `tensorflow` from `__init__.py` and other model-agnostic locations.
- [x] Create a chunk reader subroutine for PyTorch that either uses PyTorch commands directly, or allows the PyTorch execution graph to invoke `large_image` using a mechanism similar to TensorFlow's `py_function(...)`.  (Deferred: ~~If appropriate, explore the use of cuCIM and DALI as alternatives.~~)
- [x] Build the part of the PyTorch execution graph that reads chunks.
- [x] Build the part of the PyTorch execution graph that splits chunks into tiles.
- [x] Build the part of the PyTorch execution graph that transforms the image and annotation data into the form usually expected by PyTorch models.
- [x] Create a `WrappedModel` template for transforming a pixels-only PyTorch model into a pixels-and-annotation model.

**Comment by Leengit** [comment]
@cooperlab says: see this as a draft: https://github.com/PathologyDataScience/mil/blob/dev/mil/io/utils.py

**Comment by cooperlab** [comment]
@Leengit this issue touches on the reader modularity - can we use the same python file-reading function to both TF and PyTorch. Subsequent steps like cropping, etc. will be different. But what the reader takes and returns can maybe be the same in both cases. Generally, what interface does a reader have to follow.
