### ISSUE TITLE
PERF: Slowness with masked whole-slide image

### ISSUE THREAD

**Issue by Leengit** [DigitalSlideArchive/HistomicsStream#91]
Lee C. has an example with mask that is slower than he expects.  Reproduce it, analyze it, improve its performance.

**Comment by Leengit** [comment]
This may or may not be closely related to Issue #103 and thus might be solved by Pull Request #106.

**Comment by cooperlab** [comment]
I looked at this and it's just related to having a high-resolution mask. I examined the masking code and it's efficient. If a new idea springs to mind I can implement and propose a change.
